### ISSUE TITLE
Should SPARQL Update option be visible in Workbench?

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#168]
Right now, the SPARQL Update query type option is available in the drop down within the Workbench, but Rodolfo told me that SPARQL update is disabled. Is that true? If so, shouldn't we disable the option in the Workbench for now?

**Comment by MiguelAraCo** [comment]
The SPARQL client can be used with any SPARQL endpoint so it does add value. Also, the platform will re-enable support for SPARQL update in a few days so making any change is unnecessary.
