### ISSUE TITLE
Update docker image short and long description

### ISSUE THREAD

**Issue by MiguelAraCo** [CarbonLDP/carbonldp-workbench#17]
https://hub.docker.com/r/carbonldp/carbonldp-workbench/

**Comment by alvaro9210** [comment]
The descriptions for Workbench and Platform were already sent to @MiguelAraCo 
The changes must be approved and integrated by him into Docker Hub.

**Comment by MiguelAraCo** [comment]
Duplicate of CarbonLDP/carbonldp.private#18
