### ISSUE TITLE
Users should not be able to delete App admin role

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#26]
In the latest version 0.7.1 of the Workbench, the Delete icon is enabled when the App admin role is selected. Also, if I click the delete icon, while on the App admin role, it takes me to the next screen asking me if I'm sure I want to go ahead. The delete icon should not be enabled when that role is selected and the user should not be presented with the option to delete the root Admin role for an app.

**Comment by MiguelAraCo** [comment]
Focus has shifted to the new version and this issue in particular won't be ported.
