### ISSUE TITLE
Platform version unrecognized by Workbench v0.8.0

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#28]
In Workbench v0.8.0, my Platform version is unrecognized, though I know it is running and I can login to the Workbench and create an App.

![no-running-platform](https://cloud.githubusercontent.com/assets/7317733/25031935/d230bd0a-2095-11e7-9c2b-ac9a53f970f0.jpg)

**Comment by alvaro9210** [comment]
In which ports is your platform running? http://localhost:8083? 
Did you change the environment variables when running the docker command to fire up the workbench?

**Comment by codyburleson** [comment]
My platform instance is running on port 8083. I did not change environment variables when starting the Workbench. As per the guide, I used the following command initially:

```
docker run -d --name carbonldp-workbench -p 8000:80 \
    -e "CARBON_HOST=localhost:8083" \
    -e "CARBON_PROTOCOL=http" \
    carbonldp/carbonldp-workbench:latest
```
Afterwards, I use the command `docker start carbonldp-workbench` to start the container when it is stopped.

**Comment by alvaro9210** [comment]
I've just installed docker and ran the `platform` and `workbench` instances on a new machine and everything is working as supposed. 
I can't reproduce the issue. 
Can you paste the platform version by visiting the following url: http://localhost:8083/platform/api

**Comment by codyburleson** [comment]
`<version xmlns="https://carbonldp.com/ns/v1/platform#" rdf:datatype="http://www.w3.org/2001/XMLSchema#string">0.42.3</version>`

**Comment by codyburleson** [comment]
OK, I figured out the problem and it's on my end. I'm closing this issue. For local development purposes, I had done an override my data path in config.properties like this:

`# overrides from /resources/config.properties
# repositories.directory = /Users/cburleson/carbon/data`

This is only necessary or valid when using the codebase. But, I had shifted over to the actual container instead of running the platform from the container instead of from within my IDE. This was also causing a couple of other issues that stumped me. So, I commented out the above line (since using the container and not the codebase) and voila - it was resolved. Sorry!
