### ISSUE TITLE
Refactor to match the new structure of the platform 

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-workbench#29]
We need to refactor the platform to address the implications of the new version of the platform.
What needs to be addresed is the following:
1. Move Panel components to Workbench
2. Delete unnecessary components
    - My Apps
    - Create App
    - Edit App
6. Find and delete more unnecessarry components
7. Add instance & platform configuration screen
8. Rename Agents to User
9. Remove app contexts and use the carbon context instead
10. Show hidden documents in document explorer
11. Change angular-carbonldp to work with single contexts

**Comment by MiguelAraCo** [comment]
This issue was split into multiple ones.
