### ISSUE TITLE
Compatibility issues with platform v6

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-workbench#54]
The Workbench breaks when trying to display the version and the information of the platform.
This only occurs on `v1.0.0-alpha.6` of the platform.
The issue was reported by @alex-arriaga through the Carbon LDP Gitter channel.
![](https://files.gitter.im/CarbonLDP/carbonldp/1sEb/Screen-Shot-2017-12-05-at-3.34.48-PM.png)

**Comment by roddolf** [comment]
This issue is because how the browser implement the caching of resources.

The SDK will implement the fix.
See: CarbonLDP/carbonldp-js-sdk#213
