### ISSUE TITLE
Disable delete option for system managed documents 

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#62]
In Workbench: v1.0.0-alpha.2, I am able to select ".system/" and "vocabularies/", click the delete button, and get to the delete confirmation view...

![are_you_sure](https://user-images.githubusercontent.com/7317733/35575067-15c34e20-05a1-11e8-979c-daa388aa01fb.jpg)

I did not attempt to click Yes to delete one of these containers. However, since these are system containers, should we be able to even get this far? I would expect that maybe we want to either disable the delete button for those two containers or provide a special message when you attempt to delete them.

**Comment by MiguelAraCo** [comment]
Related: CarbonLDP/carbonldp-platform.private#221

**Comment by alvaro9210** [comment]
We need to make the Workbench to disable the delete buttons following the proposed platform way of handling these kind of operations.
