### ISSUE TITLE
Provide immediate feedback when deleting a document

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#63]
In the Workbench, I had a container, "quotes/" with many children (probably like 126 direct member children). To clean up, I went to delete the parent container. I got the confirmation dialog as shown below (except the one I am showing below is just for example)...

![confirm_dialog](https://user-images.githubusercontent.com/7317733/35575160-53ab4814-05a1-11e8-9be6-a54274af9026.jpg)

I clicked the red Yes button to confirm my desire to delete. Nothing appeared to happen, but I waited just in case. Sure enough, after a few seconds, the confirmation dialog disappeared and I could see that my "quote/" container was gone.

We need to have immediate feedback when the user clicks "Yes". I would expect to see an animated spinner, for example, showing me that the system has accepted my request and is working.

I think this should be required for Release 1.

I noticed when deleting an empty container, the dialog disappears and I see a spinner icon very briefly. So it seems the functionality is intended to be there. But, in the case of a container with many children, I did not see it. I think, perhaps, it's trying to show the spinner after the work, rather than before it?

**Comment by alvaro9210** [comment]
PR #77 - was created, it add a spinner to the Yes button.
@codyburleson just to clarify, the spinner icon you mentioned is not from the delete action, it instead is an indicator that a document is being loaded. (Action performed after every delete).
