### ISSUE TITLE
Label "Schedule a Backup" is misleading

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#64]
It appears to me that you can only run a backup on-demand. The label, therefore, "Schedule a backup", is currently misleading. Maybe we put this with the intent of providing schedule capability, but unless and until we have it, I would suggest we state the function more explicitly.

**Comment by MiguelAraCo** [comment]
Focus has shifted to the new version and this issue in particular won't be ported.
