### ISSUE TITLE
Workbench should not require attributes not required by REST API (app description)

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#65]
Currently, we have not indicated anywhere that an App description is required by the REST API. Indeed, it is possible to create a new app without a description when using the REST API. But, within the Workbench, this field (in the New App form) is required. I think it will be best to keep the Workbench as closely aligned to the REST API as possible in that regard. It's arguable, perhaps, but it did cause some minor confusion for me when attempting to edit an app AFTER creating the app through the REST API.

**Comment by MiguelAraCo** [comment]
Focus has shifted to the new version and this issue in particular won't be ported.
