### ISSUE TITLE
App cache is not refreshed after changing Allow all orgins on app created by REST API. 

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#66]
If you use the REST API to create a new application and then use the Workbench to verify it visually, you run into problems. Suppose the example, for example, from the Getting Started with the REST API:

```
POST /platform/apps/ HTTP/1.1
Host: localhost:8083
Content-Type: application/trig
Prefer: http://www.w3.org/ns/ldp#Container; rel=interaction-model
Slug: taxonomy-hub
Authorization: Basic amFuZS5kb2VAZXhhbXBsZS5vcmc6amFuZTEyMw==
Cache-Control: no-cache
Postman-Token: 6ef4a0c0-7c6b-50bf-3463-ea52e6e9e209

@prefix c:			<https://carbonldp.com/ns/v1/platform#>.
@prefix cs:			<https://carbonldp.com/ns/v1/security#>.

<>{
    <>
        a cs:Application;
        cs:name "Taxonomy Hub".
}
```

Issue the POST to create the app. Then you will see the app in the list of apps within the Workbench. At that point, if you go to the Document Explorer, you'll get an error because you need to turn on Allow all origins. So click over, turn on Allow all origins (and add an app description as required) then save. Now, navigate back into the Document Explorer and the error is still there.

I believe that a full page refresh will remedy the issue, but I don't think we should expect users to figure that out.

**Comment by alvaro9210** [comment]
Focus has changed to Carbon v1.0.0
Since the App context was removed form this version, i'm closing this issue.
