### ISSUE TITLE
Workbench seems to have issues in Safari

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-workbench#8]
We should be shooting to support evergreen browsers, I think (e.g. latest versions of Chrome, Firefox, Internet Explorer, and Safari). Recently I worked with a BETA user who was using Safari and witnessed several issues in the workbench, which the user did not experience when using Chrome. When executing my own test in Safari, I note that not all of my applications show in the list of applications on the dashboard (empty rows show, however). There are other issues too, which I think you'll find if you check in Safari.

![issuesinsafari](https://cloud.githubusercontent.com/assets/7317733/18810154/843fceea-8254-11e6-872d-7c722a5906ba.jpg)

If, for the BETA, there is very good reason for us to exclude Safari (from a cost/benefit perspective), we need to make an issue to be sure to clearly denote browser support for the Workbench in public documentation. In that case, we should probably also test for browser and present some kind of message to the user that it is an unsupported browser.

**Comment by MiguelAraCo** [comment]
Closed in favor of #68
